apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: access-kfserving
  namespace: kubeflow
rules:
- apiGroups: ["serving.kubeflow.org"]
  resources: ["inferenceservices"]
  verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kfserving-access-role
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-kfserving
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow
